export default [
  {
    files: ['scripts/subscription-monitor-browser.js'],
    languageOptions: {
      globals: {
        sleep: 'readonly',
        closeTab: 'readonly',
        snapshot: 'readonly',
        googleAccounts: 'readonly',
        gmail: 'readonly',
        listBrowserTabs: 'readonly',
        openTab: 'readonly',
      },
    },
  },
  {
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      globals: {
        console: 'readonly',
        process: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        clearInterval: 'readonly',
        setInterval: 'readonly',
        setImmediate: 'readonly',
        URL: 'readonly',
        URLSearchParams: 'readonly',
        Buffer: 'readonly',
        TextDecoder: 'readonly',
        TextEncoder: 'readonly',
        fetch: 'readonly',
        Headers: 'readonly',
        AbortController: 'readonly',
        AbortSignal: 'readonly',
        structuredClone: 'readonly',
      },
    },
    rules: {
      'no-unused-vars': ['warn', { argsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_' }],
      'no-undef': 'error',
      'no-constant-condition': 'warn',
      'no-unreachable': 'error',
      'no-dupe-keys': 'error',
      'no-duplicate-case': 'error',
      'eqeqeq': ['warn', 'smart'],
    },
  },
  {
    // Classic browser scripts loaded by report.html after its inline <script>,
    // whose top-level bindings (D, H, render, ...) they share.
    files: ['skills/token-usage-report/assets/*.js'],
    languageOptions: {
      sourceType: 'script',
      globals: {
        window: 'readonly',
        document: 'readonly',
        navigator: 'readonly',
        localStorage: 'readonly',
        innerWidth: 'readonly',
        addEventListener: 'readonly',
        Blob: 'readonly',
        PriceCore: 'readonly',
        D: 'writable',
        H: 'writable',
        V: 'writable',
        M: 'writable',
        Q: 'writable',
        C: 'readonly',
        f: 'readonly',
        esc: 'readonly',
        list: 'readonly',
        metric: 'readonly',
        rate: 'readonly',
        kst: 'readonly',
        render: 'readonly',
        draw: 'readonly',
        drawQuota: 'readonly',
      },
    },
  },
];
